--- 
name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v2

      - name: SET SHORT SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> GITHUB_ENV

      - name: BUILD DOCKER IMAGE
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/complete-devops-project:${{ env.SHORT_SHA}} .

      - name: LOGIN TO DOCKERHUB
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: PUSH TO DOCKERHUB
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/complete-devops-project:${{ env.SHORT_SHA }}